#!/usr/bin/env python3
"""
CosmicFlux Offline Render Harness

Mimics conductor.generate_orc to build a complete Csound orchestra+score,
then renders test signals through the instrument with various control scenarios.
"""

import os
import sys
import json
import subprocess
import numpy as np
import soundfile as sf
from pathlib import Path

# Ensure we can find the instrument
DEV_DIR = Path(__file__).parent
INSTR_DIR = DEV_DIR.parent
INSTR_FILE = INSTR_DIR / "cosmicflux.instr"
OUTPUT_DIR = DEV_DIR / "output"
SCENARIOS_DIR = DEV_DIR / "scenarios"

def parse_nebconfig(instr_content):
    """Extract nebconfig settings from instrument file"""
    config = {"sr": 48000, "ksmps": 64}
    
    in_config = False
    for line in instr_content.split('\n'):
        line = line.strip()
        if line == "nebconfigbegin":
            in_config = True
        elif line == "nebconfigend":
            in_config = False
        elif in_config and ',' in line:
            parts = line.split(',')
            key = parts[0].strip()
            if key == "sr":
                config["sr"] = int(parts[1].strip())
            elif key == "ksmps":
                config["ksmps"] = int(parts[1].strip())
    
    return config

def get_instr_body(instr_content):
    """Extract the instrument body (after nebconfigend)"""
    parts = instr_content.split("nebconfigend", 1)
    if len(parts) == 2:
        return parts[1]
    return instr_content

def build_orchestra_header(sr, ksmps):
    """Build the standard Nebulae orchestra header with chnexport globals"""
    header = f"""
; Generated by CosmicFlux render harness
sr = {sr}
ksmps = {ksmps}
nchnls = 2
0dbfs = 1

; Primary controls
gkpitch chnexport "pitch", 1
gkspeed chnexport "speed", 1
gkloopstart chnexport "start", 1
gkloopsize chnexport "size", 1
gkdensity chnexport "density", 1
gkoverlap chnexport "overlap", 1
gkwindow chnexport "window", 1
gkfilesel chnexport "file", 1
gkfreeze chnexport "freeze", 1
gkreset chnexport "reset", 1
gkblend chnexport "blend", 1
gkrecord chnexport "record", 1
gkfilestate chnexport "filestate", 1
gksource chnexport "source", 1
gksourcegate chnexport "sourcegate", 1
gksourcebuttonstate chnexport "source_state", 1
gkeol chnexport "eol", 2
gksizestatus chnexport "sizestatus", 2
gkrecordstatus chnexport "recordstatus", 2
gkbufferlength chnexport "bufferlength", 2

; Secondary controls
gkloopstart_alt chnexport "start_alt", 1
gkloopsize_alt chnexport "size_alt", 1
gkdensity_alt chnexport "density_alt", 1
gkoverlap_alt chnexport "overlap_alt", 1
gkwindow_alt chnexport "window_alt", 1
gkfreeze_alt chnexport "freeze_alt", 1
gkrecord_alt chnexport "record_alt", 1
gkfile_alt chnexport "file_alt", 1
gkreset_alt chnexport "reset_alt", 1
gksource_alt chnexport "source_alt", 1
gkpitch_alt chnexport "pitch_alt", 1
gkblend_alt chnexport "blend_alt", 1

; File data buffers (empty for effects)
gilen[] init 100
gichn[] init 100
gSname[] init 100
gisr[] init 100
gipeak[] init 100
ginumfiles init 0
"""
    return header

def build_scenario_instrument(scenario):
    """Build a harness instrument that sets controls from a scenario"""
    
    instr = """
instr 99
    ; Harness instrument to drive controls
    ; This runs alongside instr 1 and sets the gk* globals
    
"""
    
    # Static controls
    if "static" in scenario:
        for control, value in scenario["static"].items():
            instr += f"    gk{control} = {value}\n"
    
    # Automation (linear ramps)
    if "automation" in scenario:
        for control, auto in scenario["automation"].items():
            start_val = auto["start"]
            end_val = auto["end"]
            start_time = auto.get("start_time", 0)
            dur = scenario.get("duration", 10.0)
            end_time = auto.get("end_time", dur)
            
            instr += f"    gk{control} linseg {start_val}, {end_time - start_time}, {end_val}\n"
    
    # Gates (sustained triggers - stay high after first trigger)
    if "gates" in scenario:
        for control, times in scenario["gates"].items():
            instr += f"    ; Gate toggle for {control}\n"
            for i, t in enumerate(times):
                if i == 0:
                    # First trigger: set to 1 and stay there
                    instr += f"    if (timeinsts() >= {t} && timeinsts() < {t + 0.05}) then\n"
                    instr += f"        gk{control} = 1\n"
                    instr += f"    endif\n"
                else:
                    # Subsequent triggers: toggle
                    instr += f"    if (timeinsts() >= {t} && timeinsts() < {t + 0.05}) then\n"
                    instr += f"        gk{control} = 1 - gk{control}\n"
                    instr += f"    endif\n"
    
    instr += "endin\n"
    
    return instr

def render_scenario(scenario_file, input_audio, output_audio):
    """Render a scenario through the instrument"""
    
    print(f"\nRendering scenario: {scenario_file.name}")
    
    # Load scenario
    with open(scenario_file, 'r') as f:
        scenario = json.load(f)
    
    duration = scenario.get("duration", 10.0)
    
    # Read instrument file
    with open(INSTR_FILE, 'r') as f:
        instr_content = f.read()
    
    # Parse config
    config = parse_nebconfig(instr_content)
    sr = config["sr"]
    ksmps = config["ksmps"]
    
    # Build complete orchestra
    orc = build_orchestra_header(sr, ksmps)
    orc += get_instr_body(instr_content)
    orc += build_scenario_instrument(scenario)
    
    # Build score
    sco = f"""
; Start main instrument and harness
i1 0 {duration}
i99 0 {duration}
"""
    
    # Write temp files
    temp_orc = DEV_DIR / "temp.orc"
    temp_sco = DEV_DIR / "temp.sco"
    
    with open(temp_orc, 'w') as f:
        f.write(orc)
    with open(temp_sco, 'w') as f:
        f.write(sco)
    
    # Run Csound
    cmd = [
        "csound",
        "-d",  # Suppress displays
        "-m0",  # Minimal messages
        "-o", str(output_audio),
        "-i", str(input_audio),
        str(temp_orc),
        str(temp_sco)
    ]
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        
        if result.returncode != 0:
            print(f"  ERROR: Csound failed with return code {result.returncode}")
            print(f"  stdout: {result.stdout}")
            print(f"  stderr: {result.stderr}")
            return False
        
        print(f"  ✓ Rendered successfully: {output_audio.name}")
        return True
        
    except subprocess.TimeoutExpired:
        print(f"  ERROR: Csound render timed out (>120s)")
        return False
    except FileNotFoundError:
        print(f"  ERROR: Csound not found. Install Csound 6+ and ensure it's in PATH")
        return False
    finally:
        # Clean up temp files
        if temp_orc.exists():
            temp_orc.unlink()
        if temp_sco.exists():
            temp_sco.unlink()

def analyze_output(audio_file, scenario_name, input_file=None):
    """Analyze rendered output for common issues"""
    
    print(f"\n  Analyzing: {scenario_name}")
    
    try:
        audio, sr = sf.read(audio_file)
    except Exception as e:
        print(f"  ✗ Failed to read audio: {e}")
        return False
    
    # Ensure stereo
    if audio.ndim == 1:
        audio = audio.reshape(-1, 1)
    
    # Load input for level comparison if provided
    input_audio = None
    input_rms = None
    if input_file and input_file.exists():
        try:
            input_audio, input_sr = sf.read(input_file)
            if input_audio.ndim == 1:
                input_audio = input_audio.reshape(-1, 1)
            # Calculate RMS of input
            input_rms = np.sqrt(np.mean(input_audio**2))
        except:
            pass
    
    issues = []
    
    # Check for NaN/Inf
    if np.any(np.isnan(audio)):
        issues.append("Contains NaN values")
    if np.any(np.isinf(audio)):
        issues.append("Contains Inf values")
    
    # Check for DC offset
    dc_l = np.mean(audio[:, 0])
    dc_r = np.mean(audio[:, 1]) if audio.shape[1] > 1 else 0
    if abs(dc_l) > 0.01 or abs(dc_r) > 0.01:
        issues.append(f"DC offset: L={dc_l:.4f}, R={dc_r:.4f}")
    
    # Check peak level
    peak = np.max(np.abs(audio))
    if peak > 0.95:
        issues.append(f"Peak exceeds 0.95 ({peak:.3f})")
    elif peak < 0.001 and "silence" not in scenario_name.lower():
        issues.append(f"Peak too low ({peak:.6f}) - possibly silent")
    
    # Check for clipping (consecutive samples at max)
    clipping = 0
    for ch in range(audio.shape[1]):
        for i in range(len(audio) - 1):
            if abs(audio[i, ch]) > 0.95 and abs(audio[i+1, ch]) > 0.95:
                clipping += 1
    if clipping > sr * 0.01:  # More than 10ms of clipping
        issues.append(f"Sustained clipping detected ({clipping} samples)")
    
    # RMS per second (to check for decay and sustain)
    samples_per_sec = sr
    rms_per_sec = []
    for i in range(0, len(audio), samples_per_sec):
        chunk = audio[i:i+samples_per_sec]
        if len(chunk) > 0:
            rms = np.sqrt(np.mean(chunk**2))
            rms_per_sec.append(rms)
    
    # Overall RMS
    overall_rms = np.sqrt(np.mean(audio**2))
    
    # Print RMS summary
    if len(rms_per_sec) > 0:
        print(f"    RMS per second: {[f'{r:.4f}' for r in rms_per_sec[:10]]}")
        if len(rms_per_sec) > 10:
            print(f"                    (showing first 10 of {len(rms_per_sec)} seconds)")
        print(f"    Overall RMS: {overall_rms:.4f}")
    
    # Check level matching with input if available
    if input_rms is not None and overall_rms > 0.001:
        rms_ratio_db = 20 * np.log10(overall_rms / input_rms) if input_rms > 0 else 0
        print(f"    Input RMS: {input_rms:.4f}, Output RMS: {overall_rms:.4f} ({rms_ratio_db:+.1f} dB)")
        # For scenarios with 50% mix or higher, expect output within ~3 dB of input
        if '50' in scenario_name or 'mix' in scenario_name.lower():
            if abs(rms_ratio_db) > 6:
                issues.append(f"RMS mismatch: {rms_ratio_db:+.1f} dB from input (expected within ±6 dB)")
    
    # Check freeze stability if this is a freeze scenario
    if 'freeze' in scenario_name.lower() and len(rms_per_sec) > 10:
        # Find where signal settles (after initial transient)
        settle_idx = 5  # Start checking after 5 seconds
        if len(rms_per_sec) > settle_idx + 10:
            settled_rms = rms_per_sec[settle_idx:settle_idx+10]
            if len(settled_rms) > 0:
                rms_mean = np.mean(settled_rms)
                rms_std = np.std(settled_rms)
                if rms_mean > 0.001:
                    rms_var_db = 20 * np.log10((rms_mean + rms_std) / (rms_mean - rms_std + 1e-10))
                    print(f"    Freeze stability: RMS {rms_mean:.4f} ± {rms_std:.4f} ({rms_var_db:.1f} dB variation)")
                    if rms_var_db > 3:
                        issues.append(f"Freeze unstable: {rms_var_db:.1f} dB variation (expected < 2 dB)")
    
    # Report
    if issues:
        print(f"  ✗ Issues found:")
        for issue in issues:
            print(f"    - {issue}")
        return False
    else:
        print(f"  ✓ Analysis passed (peak={peak:.3f})")
        return True

def main():
    """Main render harness"""
    
    print("=" * 60)
    print("CosmicFlux Offline Render Harness")
    print("=" * 60)
    
    # Check Csound
    try:
        result = subprocess.run(["csound", "--version"], capture_output=True, text=True)
        version_line = result.stdout.strip().split('\n')[0] if result.stdout else ""
        if version_line:
            print(f"Csound: {version_line}")
        else:
            print("Csound installed (version detection failed)")
    except FileNotFoundError:
        print("ERROR: Csound not found. Install Csound 6+ and ensure it's in PATH")
        return 1
    
    # Create output directory
    OUTPUT_DIR.mkdir(exist_ok=True)
    
    # Find scenarios
    if not SCENARIOS_DIR.exists():
        print(f"ERROR: Scenarios directory not found: {SCENARIOS_DIR}")
        return 1
    
    scenario_files = sorted(SCENARIOS_DIR.glob("*.json"))
    if not scenario_files:
        print(f"ERROR: No scenario files found in {SCENARIOS_DIR}")
        return 1
    
    print(f"\nFound {len(scenario_files)} scenario(s)")
    
    # Find input audio files
    test_signals_dir = DEV_DIR / "test_signals"
    if not test_signals_dir.exists():
        print(f"\nERROR: Test signals directory not found: {test_signals_dir}")
        print("Run generate_test_signals.py first")
        return 1
    
    input_files = sorted(test_signals_dir.glob("*.wav"))
    if not input_files:
        print(f"ERROR: No test signals found in {test_signals_dir}")
        return 1
    
    print(f"Found {len(input_files)} test signal(s)")
    
    # Render each scenario with each input
    results = []
    for scenario_file in scenario_files:
        scenario_name = scenario_file.stem
        
        for input_file in input_files:
            input_name = input_file.stem
            output_name = f"{scenario_name}_{input_name}.wav"
            output_file = OUTPUT_DIR / output_name
            
            success = render_scenario(scenario_file, input_file, output_file)
            
            if success and output_file.exists():
                analysis_ok = analyze_output(output_file, output_name, input_file)
                results.append((output_name, success and analysis_ok))
            else:
                results.append((output_name, False))
    
    # Summary
    print("\n" + "=" * 60)
    print("RENDER SUMMARY")
    print("=" * 60)
    
    passed = sum(1 for _, ok in results if ok)
    total = len(results)
    
    for name, ok in results:
        status = "✓" if ok else "✗"
        print(f"  {status} {name}")
    
    print(f"\nPassed: {passed}/{total}")
    
    if passed == total:
        print("\n✓ All tests passed!")
        return 0
    else:
        print(f"\n✗ {total - passed} test(s) failed")
        return 1

if __name__ == "__main__":
    sys.exit(main())
